// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Media struct {
	ID       string   `json:"id"`
	Cid      string   `json:"cid"`
	FileType string   `json:"file_type"`
	Caption  string   `json:"caption"`
	Tags     []string `json:"tags"`
	Star     bool     `json:"star"`
	Pin      bool     `json:"pin"`
}

type Origin struct {
	ID          string `json:"id"`
	IndexCid    string `json:"index_cid"`
	Name        string `json:"name"`
	Description string `json:"description"`
}
